apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo-svc
  name: odoo-svc
  namespace: icgroup
spec:
  ports:
  - name: 8069-8069
    port: 8069
    protocol: TCP
    targetPort: 8069
    nodePort: 30069
  selector:
    app: odoo-svc
  type: NodePort

