apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  label:
    env: prod
    app: odoo
  namespace: icgroup
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual