---
# defaults file for pgadmin_role

pg_admin_init_config_name: pgadmin
pg_admin_init_config_group: postgres_group
pg_admin_init_config_host: postgres
pg_admin_init_config_username: odoo_user

pgadmin_service_name: pgadmin
pgadmin_image:  dpage/pgadmin4
pgadmin_port: 80
pgadmin_networks: pgadmin_networks
pgadmin_default_email: odoo@odoo.com
pgadmin_default_password: odoo
pgadmin_volumes: pgadmin_data